### ISSUE TITLE
5分钟快速上手Compass

### ISSUE THREAD

**Issue by codexu** [codexu/notes#8]
Sass是一种"CSS预处理器"，可以让CSS的开发变得简单和可维护。但是，只有搭配Compass，它才能显出真正的威力，学会了Compass，你的CSS开发效率会上一个台阶。

Compass与CSS的关系类似于JQuery与JavaScript，封装了一系列有用的模块和模板，补充Sass的功能。

## 一、安装

-  Compass是用Ruby语言开发的，所以安装它之前，必须安装[Ruby](http://www.ruby-lang.org/en/downloads/)。

- 命令行模式（windows去掉sodu）

  `sudo gem install compass`

  Compass是基于Sass的，所以Ruby会自动帮我们安装好Sass。

- 如果gem安装失败，可以[手动下载](https://rubygems.org/gems/compass)。

  命令行模式（windows去掉sodu）

  `Sudo gem install --local compass.gem`

## 二、项目初始化&编译

- 创建compass项目(命令行模式)

  `compass create myproject`

  `cd myproject`

- Compass编译命令

  `compass compile`

- Compass自动编译命令

  `compass watch`

## 三、Compass模块

Compass内置五个模块，分别为`reset` `css3` `layout` `typography` `utilities`。

- reset模块：重置浏览器默认样式

  `@import "compass/reset";`

- css3模块：提供19种CSS3命令，为css3属性添加不同浏览器兼容性前缀

  以transition属性为例`transition: all .5s;`

  ```scss
  @import "compass/css3";
  @include transition(all,.5s);
  ```
  编译结果为：
  ```scss
  -moz-transition: all, 0.5s;
  -o-transition: all, 0.5s;
  -webkit-transition: all, 0.5s;
  transition: all, 0.5s;
  ```

- layout模块：提供布局功能

  以`sticky-footer()`为例，指定的元素始终会出现在浏览器最低端

  ```scss
  @import "compass/layout";
  @include sticky-footer(54px);
  ```

- Typography 模块：提供版式功能

  以<a>链接为例，使用`link-colors()`为不同状态下设置不同的color

  ```scss
  @import "compass/typography";
  @include link-colors(#00c, #0cc, #c0c, #ccc, #cc0);
  ```

-  utilities模块：该模块提供某些不属于其他模块的功能。

  例如做一个清除浮动的class
  ```scss
  import "compass/utilities/";
  .clearfix {
  　　@include clearfix;
  }
  ```

- 除了这5个模块，Compass还提供了一系列好用的函数。

  例如如`image-width()`和`image-height()`返回图片的宽和高。
  ```scss
  $pic_path: "../images/pic.jpg";
  #pic{
    background: url($pic_path);
    width: image-width($pic_path);
    height: image-height($pic_path);
  }
  ```
  返回结果
  ```scss
  #pic {
    background: url("../images/pic.jpg");
    width: 590px;
    height: 100px;
  }
  ```
  这么做，以后就省去引入图片时，还要查看图片大小的问题了。

## 四、利用Gulp自动化编译

- 命令行模式安装依赖库

  `npm install gulp gulp-watch gulp-compass --save-dev`

- 创建`gulpfile.js`文件
  ```javascript
  const gulp = require('gulp');
  const watch = require('gulp-watch');
  const compass = require('gulp-compass');

  // 配置compass
  gulp.task('compass', function() {
    gulp.src('./sass/*.scss')
      .pipe(compass({
        config_file: './config.rb',
        css: 'stylesheets',
        sass: 'sass'
      }))
      .pipe(gulp.dest('./stylesheets'))
  })

  // 监听sass文件
  gulp.task('auto', function() {
    gulp.watch('./sass/*.scss', ['compass'])
  })

  // 默认动作
  gulp.task('default', ['auto', 'compass'])
  ```

- 命令行模式`gulp`
